[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2

[dependencies]
gsim = { git = "https://github.com/Artentus/gsim.git", features = ["yosys-import", "dot-export", "tracing"] }

[build-dependencies]
glob = "0.3.1"
